spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true



jwt:
  secret: thisisaverylongsecretkeythatisatleast256bitslong123456789